### ISSUE TITLE
gSACA-K fails on empty string

### ISSUE THREAD

**Issue by votroto** [felipelouza/gsa-is#1]
Implementation causes a segmentation fault when the input contains at least one empty string.

## Example input 
In your notation `a$b$$d$#`.

## Expected output 
Suffixes should be sorted as usual + the document index in DA, empty-suffix pointer in SA and a 0 in the LCP array.

I reckon:
```
i       SA      DA      LCP     suffixes
0       8       4       0       #
1       1       0       0       $b$$d$#
2       3       1       0       $$d$#
3       4       2       0       $d$#
4       6       3       0       $#
5       0       0       0       a$b$$d$#
6       2       1       0       b$$d$#
7       5       3       0       d$#
```

## Actual output
Segmentation fault.

## Workaround
Add a dummy token to all empty strings.

**Comment by felipelouza** [comment]
Hi, why do you need to handle empty strings? Or, do you just want that the algorithm checks if there is at least one empty string before start?
Thank you!

**Comment by votroto** [comment]
The simplest argument is that it violates the Robustness Principle. An even shallower reason is that, when using property based testing, an empty string is the first input the algorithm receives. One way or another an empty string is going to show up and, as it stands, every user is going to have to work around this limitation. If there is a clear and obvious way to solve this, it would be great if it was already implemented. :)

**Comment by votroto** [comment]
If you were asking about real life examples, then for example when checking ASCII documents some of them might be empty, in which case neither a crash nor an error message are desirable.

**Comment by felipelouza** [comment]
Ok, I understand. I will think if there is a trivial solution.

**Comment by felipelouza** [comment]
Hi, sorry the late reply. Unfortunately, there is no easy way to add support for empty strings, since the algorithm needs that each LMS-substring have size at least 3. I just added a macro to check if there is an empty string and return -2 ([code](https://github.com/felipelouza/gsa-is/blob/master/gsacak.c#L21)).
